import random
"""
Flash cards
Other features I would add
- menu selection between sentences and translations
- make a multiselect feature for multiple dictionaries
- Make an OpenAI integration so that I could make AI-generated sentences 
"""

words = {
    'welkom (in)':'welcome (to)',
    'goedemorgen':'good morning',
    'allemaal':'everyone',
    'de cursus':'course',
    'de':'the',
    'Nederlands':'Dutch',
    'ik':'I',
    'zijn':'is',
    'jullie':'your (plural)',
    'de docent':'teacher',
    'jullie':'you (plural)',
    'hebben':'have',
    'twee':'two',
    'andere':'other',
    'hij':'he',
    'lesgeven':'teaches',
    'de dag':'day',
    'drie':'three',
    'we':'we',
    'beginnen (beginnen) ':'begin / start',
    'met':'with',
    'kennismaken':'get to know',
    'wie':'who',
    'ben (zijn)':'are',
    'jij':'you',
    'wat':'what',
    'jouw':'your (singular)',
    'de naam':'name',
    'mijn':'my',
    'dag':'day',
    'je':'your (singular)',
    'de voornaam':'first name',
    'de achternaam':'surname',
    'uit':'from',
    'welke (welk)':'which',
    'het land':'country',
    'Engeland':'England',
    'kom (komen)':'come',
    'de buurman':'neighbour',
    'van':'of',
    'hoe':'how (what)',
    'hoe heet jij?':"what's your name?",
    'heet (heten)':'is called',
    'waar vandaan':'where from',
    'waar':'where',
    'China':'China',
    'woon (wonen)':'live',
    'nu':'now',
    'het adres':'address',
    'het nummer':'number',
    'het antwoord':'answer',
    'nee':'no',
    'de postcode':'postal code',
    'u':'you',
    'mevrouw':'Ms / Mrs',
    'woont (wonen)':'live',
    'ook':'also',
    'in':'in',
    'zeg (zeggen)':'call (say)',
    'maar':'but (just)',
    'hoor':'(for friendliness,',
    'ja':'yes',
    'hier':'here',
    'al':'already',
    'twintig':'twenty',
    'hetjaar':'year',
    'gaan verder (verdergaan)':'go on (continue)',
    'de les':'lesson',
    'heeft (hebben)':'has',
    'iedereen':'everyone',
    'het boek':'book',
    'het':'the',
    'de tekst':'text',
    'één':'one',
    'zitten (zitten)':'are sitting',
    'de kantine':'canteen',
    'deze':'this',
    'de plaats':'seat / place',
    'vrije (vrij)':'free',
    'ja hoor':'yes',
    'zo':'okay I right',
    'een':'a(n)',
    'lekker':'nice / delicious',
    'het kopje (de kop)':'cup',
    'de koffie':'coffee',
    'al lang':'for a long time',
    'pas':'only',
    'of':'or',
    'welke':'what',
    'eigenlijk':'actually I really',
    'vandaag':'today',
    'donderdag':'Thursday',
    'augustus':'August',
    'morgen':'tomorrow',
    'ik ben jarig (jarigzijn)':"it's my birthday",
    'wat leuk':'how nice',
    'december':'December',
    'dus':'so / therefore',
    'de winter':'winter',
    'krijg (krijgen)':'get / receive',
    'nog':'any',
    'het bezoek':'visit I visitors',
    'de broer':'brother',
    'jonger (jong)':'younger',
    'maar':'but',
    'wel':'certainly',
    'langer (lang)':'taller',
    'nog meer':'any more',
    'broers (broer)':'brothers',
    'zussen (aus)':'sisters',
    'de zus':'5i5ter',
    'nog':'as well',
    'kijk (kijken)':'look',
    'de foto':'photo',
    'goh':'Oh',
    'heel':'very',
    'andere (ander)':'different / other',
    'het type':'type',
    'kort':'short',
    'blond':'blonde',
    'het haar':'hair',
    'donker':'dark',



    'de ouders':'parents',
    'komen op bezoek (op bezoek komen)':'pay a visit',
    'op dit moment':'at the moment',
    'Indonesié':'Indonesia',
    'doen (doen)':'are doing',
    'daar':'there',
    'op vakantie':'on holiday',
    'de vakantie':'holiday',
    'de vader':'father',
    'voor':'for',
    'zijn':'his',
    'het werk':'work',
    'het seizoen':'season',
    'wanneer':'when',
    'de zomer':'summer',
    'weet (weten)':'know',
    'niet':'not',
    'vertel (vertellen)':'tell',
    'eens':'(usually untranslated)',
    'over':'about',
    'de familie':'family',
    'dat':'that',
    'wil (willen)':'want / would like',
    'laat':'late',
    '11.00 uur':"11 o'clock",
    'moeten (moeten)':'should / have to',
    'weer':'again',
    'naar':'to',
    'het gezin':'family',
    'de ouders':'parents',
    'de vader':'father',
    'de moeder':'mother',
    'de man / de echgenoot':'husband',
    'de vrouw / de echtgenote':'wife',
    'het kind':'child',
    'de zoon':'son',
    'de dochter':'daughter',
    'de broer':'brother',
    'de zus':'sister',
    'de familie':'family',
    'de schoonzus':'sister in law',
    'de zwager':'brother in law',
    'de opa':'grandfather',
    'de oma':'grandmother',
    'het kleinkind':'grandchild',
    'de oom':'uncle',
    'de tante':'aunt',
    'de neef':'nephew / cousin',
    'de nicht':'niece / cousin',
    'eergisteren':'day before yesterday',
    'gisteren':'yesterday',
    'vandaag':'today',
    'morgen':'tomorrow',
    'overmorgen':'day after tomorrow',
    'maandag':'Monday',
    'dinsdag':'Tuesday',
    'woensdag':'Wednesday',
    'donderdag':'Thursday',
    'vrijdag':'Friday',
    'zaterdag':'Saturday',
    'zondag':'Sunday',
    'maand':'month',
    'januari':'January',
    'februari':'February',
    'maart':'March',
    'april':'April',
    'mei':'May',
    'juni':'June',
    'juli':'July',
    'augustus':'August',
    'september':'September',
    'oktober':'October',
    'november':'November',
    'december':'December',
    'seizoen':'season',
    'de winter':'winter',
    'de lente / het voorjaar':'spring',
    'de zomer':'summer',
    'de herfst / het najaar':'fall',
    'viert (vieren)':'is celebrating',
    'de verjaardag':'birthday',
    'het café':'café I pub',
    'samen':'together',
    'gefeliciteerd':'happy birthday',
    'dankje wel':'thank you',
    'dit is':'this is',
    'prettig met je':'pleased to meet you',
    'kennis te maken (kennismaken)':'',
    'kennen':'know (people)',
    'elkaar':'one another',
    'drinken':'drink',
    'ik trakteer (trakteren)':"it's my treat",
    'wil graag (graagwillen)':'would like',
    'de cola':'cola',
    'biertje (het bier)':'beer',
    'neem (nemen)':'have (take)',
    'rode (rood)':'red',
    'de wijn':'wine',
    'roep (roepen)':'call',
    'de Ober':'waiter',
    'mag (mogen)':'may',
    'besteilen':'order',
    'alstublieft':'please',
    'Franse (Frans)':'French',
    'Spaanse (Spaans)':'Spanish',
    'Zuid-Afrikaanse (Zuid Afrikaans)':'South African',
    'de':'the',
    'nou':'well then',
    'proost':'cheers',
    'op je verjaardag':'happy birthday',
    'bedankt':'thanks',
    'het poosje':'short while',
    'later (laat)':'later',
    'zullen (zullen)':'shall',
    'nog een keer':'once more',
    'dat is':'that is',
    'goed':'good',
    'het idee':'idea',
    'hetzelfde':'the same',
    'ja, graag':'yes please',
    'dit':'this',
    'het rondje':'round',
    'betaal (betalen)':'pay',
    'geven':'give',
    'nog maar':'another',
    'hetWas':'glass',
    'afrekenen':'pay / settte the bill',
    'alfes':'everything',
    'daarom':"that's why",
    'eerste':'first',
    'tweede':'second',
    'eerste':'first',
    'tweede':'second',
    'derde':'third',
    'vierde':'foruth',
    'vijfde':'fifth',
    'zesde':'sixth',
    'zevende':'seventh',
    'achtste':'eighth',
    'negende':'ninth',
    'tiende':'tenth',
    'elfde':'eleventh',
    'twaalfde':'twelvth',
    'dertiende':'thirteenth',
    'veertiende':'fourteenth',
    'vijftiende':'fifteenth',
    'zestiende':'sixteenth',
    'zeventiende':'seventeenth',
    'achttiende':'eighteenth',
    'negentiende':'nineteenth',
    'twintigste':'twenteeth',
    'eenentwintigste':'twenty-first',
    'honderdste':'hundredth',

    #insert H4 - H7
    "laten zien":"show", 
    "de computer":"computer",
    "derde":"third",
    "de verdieping":"floor/storey",
    "oude (oud)":"old",
    "de buurt":"neighborhood",
    "ver":"far",
    "het centrum":"city center",
    "dicht bij":"close to",
    "het park":"park",
    "de woonkamer":"living room",
    "de vierkante meter":"square meters",
    "vierkante (vierkant)":"square (adj.)",
    "de meter":"meter",
    "open":"open",
    "de keuken":"kitchen",
    "ruime (ruim)":"spacious",
    "slaapkamers (de slaapkamer)":"bedroom",
    "het balkon":"balcony",
    "het westen":"west",
    "de gang":"passage(way)",
    "de wc":"toilet",
    "eenvoudige (eenvoudig)":"simple",
    "de badkamer":"bathroom",
    "de douche":"shower",
    "hoeven":"need",
    "het bad":"bath",
    "gebruiken":"use",
    "geschikte (geschikt)":"suitable",
    "huizen (het huis)":"houses",
    "want":"because",
    "te huur":"to let",
    "huur (huren)":"rent",
    "het huisje (het huis)":"house",
    "verhuren":"to let out",
    "gemeubileerd":"furnished",
    "bedden (het bed)":"beds",
    "stoelen (de stoel)":"chairs",
    "het bureau":"desk",
    "de bank":"sofa/couch",
    "het voordeel":"advantage",
    "niets":"nothing",
    "zonnige (zonnig)":"sunny",
    "de kamer":"room",
    "benedewoning":"ground-floor flat",
    "dat lijkt me fantastisch":"that sounds great",
    "waar":"true",
    "overleggen":"discuss",
    "bel (bellen)":"call",
    "zo snel mogelijk":"as soon as possible",
    "nieuwe (nieuw)":"new",
    "een bepaald type woning":"a particular type of house",
    "de woning":"house 1",
    "het huis":"house 2",
    "de flat":"flat",
    "het appartement":"appartment",
    "de bovenwoning":"upstairs flat",
    "de benedenwoning":"ground-floor flat",
    "in en bij het huis":"in and around the house",
    "de slaapkamer":"bedroom",
    "de keuken":"kitchen",
    "ruime (ruim)":"spacious",
    "slaapkamers (de slaapkamer)":"bedrooms",
    "het balkon":"balcony",
    "het westen":"west",
    "de gang":"passage(way)",
    "de wc":"toilet",
    "eenvoudige (eenvoudig)":"simple",
    "de badkamer":"bathroom",
    "de douche":"shower",
    "hoeven":"need",
    "het bad":"bath",
    "het raam":"window",
    "de deur":"door",
    "de tuin":"garden",
    "het schuurtje":"small shed",
    "de garage":"garage",
    "het raam":"window",
    "de tafel":"table",
    "de stoel":"chair",
    "het bed":"bed",
    "de kast":"cupboard"
}

def main():
    print("Welkom bij Flashcards!")
    new_word = input_new_word()
    while new_word == "j":
        random_key = pick_word()
        print_dutch_word(random_key)
        NL_response = input_NL_response()
        test_NL_response(random_key, NL_response)
        input_new_word()

def input_new_word():
    new_word = input("(Her)starten? (j/n)")
    if new_word == "j":
       return new_word
    else:
      print("Dankje wel voor gebruiken!")
      quit()  

#Selects a random key
def pick_word():
    random_key = random.choice(list(words.keys()))
    return random_key

#Accesses the corresponding value for the selected random_key
def print_dutch_word(random_key):
    print(words[random_key])

#Asks for the NL response
def input_NL_response():
    NL_response = input("NL: ")
    return NL_response

#Checks correctness of NL response with the corresponding key
def test_NL_response(random_key, NL_response):
    if NL_response == random_key:
        print("Juist!")
    else:
        print(f"Ontjuist! De juist antwoord is: {random_key}")

if __name__ == '__main__':
    main()